name: Context examples

on: push

jobs:
    jobnamecontext:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "nudelsalat $MY_ACTION"
              env:
                MY_ACTION: ${{ github.action}}